- name: Apache
  hosts: all
  become: yes
  tasks:
    - name: Install Apache 
      apt:
        name: apache2
    - name: Start Apache 
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Stop Apache 
      service:
        name: apache2
        state: stopped
        enabled: no
  vars:
    ansible_ssh_private_key_file: "/path/to/your/your_pem_file.pem" # Replace with the path to your PEM key file
